//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraFinal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaAdicciones
    {
        public CategoriaAdicciones()
        {
            this.Adicciones = new HashSet<Adicciones>();
        }
    
        public int idCategoriaAdiccion { get; set; }
        public string nombreCategoria { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Adicciones> Adicciones { get; set; }
    }
}
