//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraFinal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int id_Cliente { get; set; }
        public int id_TipoCliente { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string nombre { get; set; }
        public int id_PaisProcedencia { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
    
        public virtual PaisProcedencia PaisProcedencia { get; set; }
        public virtual TipoCliente TipoCliente { get; set; }
    }
}
