//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraFinal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.MantAddicionxCliente = new HashSet<MantAddicionxCliente>();
            this.RegistroPoliza = new HashSet<RegistroPoliza>();
        }
    
        public int idCliente { get; set; }
        public int idUsuario { get; set; }
        public string nomCliente { get; set; }
        public string ape1Cliente { get; set; }
        public string ape2Cliente { get; set; }
        public string numCedula { get; set; }
        public string genero { get; set; }
        public string direccionFisica { get; set; }
        public string pTelefono { get; set; }
        public string sTelefono { get; set; }
        public System.DateTime ultimoIngreso { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<MantAddicionxCliente> MantAddicionxCliente { get; set; }
        public virtual ICollection<RegistroPoliza> RegistroPoliza { get; set; }
    }
}
