//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFApplication.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ClientesBDEntities : DbContext
    {
        public ClientesBDEntities()
            : base("name=ClientesBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<PaisProcedencia> PaisProcedencia { get; set; }
        public DbSet<TipoCliente> TipoCliente { get; set; }
        public DbSet<tblUsuario> tblUsuario { get; set; }
    
        public virtual int sp_EliminaCliente(Nullable<int> id_Cliente)
        {
            var id_ClienteParameter = id_Cliente.HasValue ?
                new ObjectParameter("id_Cliente", id_Cliente) :
                new ObjectParameter("id_Cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaCliente", id_ClienteParameter);
        }
    
        public virtual int sp_EliminaPaisProcedencia(Nullable<int> id_PaisProcedencia)
        {
            var id_PaisProcedenciaParameter = id_PaisProcedencia.HasValue ?
                new ObjectParameter("id_PaisProcedencia", id_PaisProcedencia) :
                new ObjectParameter("id_PaisProcedencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaPaisProcedencia", id_PaisProcedenciaParameter);
        }
    
        public virtual int sp_EliminaTipoCliente(Nullable<int> id_TipoCliente)
        {
            var id_TipoClienteParameter = id_TipoCliente.HasValue ?
                new ObjectParameter("id_TipoCliente", id_TipoCliente) :
                new ObjectParameter("id_TipoCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaTipoCliente", id_TipoClienteParameter);
        }
    
        public virtual int sp_InsertaCliente(Nullable<int> id_TipoCliente, string primerApellido, string segundoApellido, string nombre, Nullable<int> id_PaisProcedencia, string telefono1, string telefono2)
        {
            var id_TipoClienteParameter = id_TipoCliente.HasValue ?
                new ObjectParameter("id_TipoCliente", id_TipoCliente) :
                new ObjectParameter("id_TipoCliente", typeof(int));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("primerApellido", primerApellido) :
                new ObjectParameter("primerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("segundoApellido", segundoApellido) :
                new ObjectParameter("segundoApellido", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_PaisProcedenciaParameter = id_PaisProcedencia.HasValue ?
                new ObjectParameter("id_PaisProcedencia", id_PaisProcedencia) :
                new ObjectParameter("id_PaisProcedencia", typeof(int));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("telefono1", telefono1) :
                new ObjectParameter("telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("telefono2", telefono2) :
                new ObjectParameter("telefono2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaCliente", id_TipoClienteParameter, primerApellidoParameter, segundoApellidoParameter, nombreParameter, id_PaisProcedenciaParameter, telefono1Parameter, telefono2Parameter);
        }
    
        public virtual int sp_InsertaPaisProcedencia(Nullable<int> nombre)
        {
            var nombreParameter = nombre.HasValue ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaPaisProcedencia", nombreParameter);
        }
    
        public virtual int sp_InsertaTipoCliente(string nombre, string codigo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaTipoCliente", nombreParameter, codigoParameter);
        }
    
        public virtual int sp_ModificaCliente(Nullable<int> id_Cliente, Nullable<int> id_TipoCliente, string primerApellido, string segundoApellido, string nombre, Nullable<int> id_PaisProcedencia, string telefono1, string telefono2)
        {
            var id_ClienteParameter = id_Cliente.HasValue ?
                new ObjectParameter("id_Cliente", id_Cliente) :
                new ObjectParameter("id_Cliente", typeof(int));
    
            var id_TipoClienteParameter = id_TipoCliente.HasValue ?
                new ObjectParameter("id_TipoCliente", id_TipoCliente) :
                new ObjectParameter("id_TipoCliente", typeof(int));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("primerApellido", primerApellido) :
                new ObjectParameter("primerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("segundoApellido", segundoApellido) :
                new ObjectParameter("segundoApellido", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_PaisProcedenciaParameter = id_PaisProcedencia.HasValue ?
                new ObjectParameter("id_PaisProcedencia", id_PaisProcedencia) :
                new ObjectParameter("id_PaisProcedencia", typeof(int));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("telefono1", telefono1) :
                new ObjectParameter("telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("telefono2", telefono2) :
                new ObjectParameter("telefono2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaCliente", id_ClienteParameter, id_TipoClienteParameter, primerApellidoParameter, segundoApellidoParameter, nombreParameter, id_PaisProcedenciaParameter, telefono1Parameter, telefono2Parameter);
        }
    
        public virtual int sp_ModificaPaisProcedencia(Nullable<int> id_PaisProcedencia, string nombre)
        {
            var id_PaisProcedenciaParameter = id_PaisProcedencia.HasValue ?
                new ObjectParameter("id_PaisProcedencia", id_PaisProcedencia) :
                new ObjectParameter("id_PaisProcedencia", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaPaisProcedencia", id_PaisProcedenciaParameter, nombreParameter);
        }
    
        public virtual int sp_ModificaTipoCliente(Nullable<int> id_TipoCliente, string nombre, string codigo)
        {
            var id_TipoClienteParameter = id_TipoCliente.HasValue ?
                new ObjectParameter("id_TipoCliente", id_TipoCliente) :
                new ObjectParameter("id_TipoCliente", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaTipoCliente", id_TipoClienteParameter, nombreParameter, codigoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaCliente_Result> sp_RetornaCliente(string primerApellido, string nombre)
        {
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("primerApellido", primerApellido) :
                new ObjectParameter("primerApellido", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaCliente_Result>("sp_RetornaCliente", primerApellidoParameter, nombreParameter);
        }
    
        public virtual ObjectResult<sp_RetornaClienteID_Result> sp_RetornaClienteID(Nullable<int> id_Cliente)
        {
            var id_ClienteParameter = id_Cliente.HasValue ?
                new ObjectParameter("id_Cliente", id_Cliente) :
                new ObjectParameter("id_Cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaClienteID_Result>("sp_RetornaClienteID", id_ClienteParameter);
        }
    
        public virtual ObjectResult<sp_RetornaPaisProcedencia_Result> sp_RetornaPaisProcedencia(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaPaisProcedencia_Result>("sp_RetornaPaisProcedencia", nombreParameter);
        }
    
        public virtual ObjectResult<sp_RetornaPaisProcedenciaID_Result> sp_RetornaPaisProcedenciaID(Nullable<int> id_PaisProcedencia)
        {
            var id_PaisProcedenciaParameter = id_PaisProcedencia.HasValue ?
                new ObjectParameter("id_PaisProcedencia", id_PaisProcedencia) :
                new ObjectParameter("id_PaisProcedencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaPaisProcedenciaID_Result>("sp_RetornaPaisProcedenciaID", id_PaisProcedenciaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaTipoCliente_Result> sp_RetornaTipoCliente(string nombre, string codigo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaTipoCliente_Result>("sp_RetornaTipoCliente", nombreParameter, codigoParameter);
        }
    
        public virtual ObjectResult<sp_RetornaTipoClienteID_Result> sp_RetornaTipoClienteID(Nullable<int> id_TipoCliente)
        {
            var id_TipoClienteParameter = id_TipoCliente.HasValue ?
                new ObjectParameter("id_TipoCliente", id_TipoCliente) :
                new ObjectParameter("id_TipoCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaTipoClienteID_Result>("sp_RetornaTipoClienteID", id_TipoClienteParameter);
        }
    
        public virtual ObjectResult<sp_RetornaUsuario_Result> sp_RetornaUsuario(string correoElectronico, string nombreCompleto, Nullable<int> id_Usuario)
        {
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("correoElectronico", correoElectronico) :
                new ObjectParameter("correoElectronico", typeof(string));
    
            var nombreCompletoParameter = nombreCompleto != null ?
                new ObjectParameter("nombreCompleto", nombreCompleto) :
                new ObjectParameter("nombreCompleto", typeof(string));
    
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaUsuario_Result>("sp_RetornaUsuario", correoElectronicoParameter, nombreCompletoParameter, id_UsuarioParameter);
        }
    
        public virtual ObjectResult<sp_RetornaUsuarioCorreoPwd_Result> sp_RetornaUsuarioCorreoPwd(string correoElectronico, string contrasena)
        {
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("correoElectronico", correoElectronico) :
                new ObjectParameter("correoElectronico", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaUsuarioCorreoPwd_Result>("sp_RetornaUsuarioCorreoPwd", correoElectronicoParameter, contrasenaParameter);
        }
    
        public virtual ObjectResult<sp_RetornaUsuarioID_Result> sp_RetornaUsuarioID(Nullable<int> id_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaUsuarioID_Result>("sp_RetornaUsuarioID", id_UsuarioParameter);
        }
    }
}
