//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraFinal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoberturaPoliza
    {
        public CoberturaPoliza()
        {
            this.RegistroPoliza = new HashSet<RegistroPoliza>();
        }
    
        public int idCoberturaPoliza { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public double porcentaje { get; set; }
        public int idTipoPoliza { get; set; }
    
        public virtual TipoPoliza TipoPoliza { get; set; }
        public virtual ICollection<RegistroPoliza> RegistroPoliza { get; set; }
    }
}
