//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraFinal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoberturaPoliza
    {
        public CoberturaPoliza()
        {
            this.RegistroPoliza = new HashSet<RegistroPoliza>();
        }
    
        public int idCoberturaPoliza { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public double porcentaje { get; set; }
        public int idTipoPoliza { get; set; }
    
        public virtual TipoPoliza TipoPoliza { get; set; }
        public virtual ICollection<RegistroPoliza> RegistroPoliza { get; set; }
    }
}
