//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraFinal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.RegistroPoliza = new HashSet<RegistroPoliza>();
        }
    
        public int idEmpleado { get; set; }
        public int idUsuario { get; set; }
        public string nomEmpleado { get; set; }
        public string ape1Empleado { get; set; }
        public string ape2Empleado { get; set; }
        public string numCedula { get; set; }
        public int idSucursal { get; set; }
        public System.DateTime ultimoIngreso { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<RegistroPoliza> RegistroPoliza { get; set; }
    }
}
