//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraFinal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantAddicionxCliente
    {
        public int idMantAdiccionxCliente { get; set; }
        public int idAdiccion { get; set; }
        public int idCliente { get; set; }
    
        public virtual Adicciones Adicciones { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
