//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraFinal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public Sucursal()
        {
            this.Empleado = new HashSet<Empleado>();
            this.RegistroPoliza = new HashSet<RegistroPoliza>();
        }
    
        public int idSucursal { get; set; }
        public string nomSucursal { get; set; }
        public string direccion { get; set; }
        public int idTelefono { get; set; }
    
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual ICollection<RegistroPoliza> RegistroPoliza { get; set; }
        public virtual Telefono Telefono { get; set; }
    }
}
