//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraFinal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public Sucursal()
        {
            this.Empleado = new HashSet<Empleado>();
            this.RegistroPoliza = new HashSet<RegistroPoliza>();
        }
    
        public int idSucursal { get; set; }
        public string nomSucursal { get; set; }
        public string direccion { get; set; }
        public int idTelefono { get; set; }
    
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual ICollection<RegistroPoliza> RegistroPoliza { get; set; }
        public virtual Telefono Telefono { get; set; }
    }
}
