//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraFinal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public Telefono()
        {
            this.Sucursal = new HashSet<Sucursal>();
        }
    
        public int idTelefono { get; set; }
        public string telefono1 { get; set; }
        public Nullable<int> extension { get; set; }
    
        public virtual ICollection<Sucursal> Sucursal { get; set; }
    }
}
