//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraFinal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPoliza
    {
        public TipoPoliza()
        {
            this.CoberturaPoliza = new HashSet<CoberturaPoliza>();
        }
    
        public int idTipoPoliza { get; set; }
        public string nombre { get; set; }
        public string detalles { get; set; }
    
        public virtual ICollection<CoberturaPoliza> CoberturaPoliza { get; set; }
    }
}
