//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraFinal.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPoliza
    {
        public TipoPoliza()
        {
            this.CoberturaPoliza = new HashSet<CoberturaPoliza>();
        }
    
        public int idTipoPoliza { get; set; }
        public string nombre { get; set; }
        public string detalles { get; set; }
    
        public virtual ICollection<CoberturaPoliza> CoberturaPoliza { get; set; }
    }
}
